server:
  port: 18080
  error:
    include-message: always

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: post123!

  devtools:
    livereload:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

mybatis:
  mapper-locations:
    - kr/co/demtech/sdap/mapper/*.xml
  type-aliases-package: kr.co.demtech.sdap.domain
  configuration:
    map-underscore-to-camel-case: true
