server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: post123!

  web:
    resources:
      static-locations:
        - file:src/main/resources/static

  devtools:
    livereload:
      enabled: true

mybatis:
  type-aliases-package: kr.co.demtech.sdap.domain
  configuration:
    map-underscore-to-camel-case: true
